# Environment Args
output_root: 'output_dir' # '../output_root'
pytorch_data_dir: '/root/repos/vlmaps/data' # '/mnt/haiwen/datasets'

# Dataset args
dataset: "cocostuff"

# Model Args
model_type: "dinov2s_reg"
activation_type: "token"

# Upsampling args
upsampler_type: "loftup"
upsampler_path: "/root/.cache/huggingface/hub/models--haiwen--loftup-dinov2s_reg/snapshots/35b4fc9287c0411c1b68abfe47b43d5b36965792/pytorch_model.bin"

# Training args
batch_size: 8
epochs: 10
num_workers: 2
lr: 1e-4
load_size: 224 ## Input image size (to extract LR feats)
guidance_res: 224 ## Guidance image size (to extract HR feats) -- same as HR feat size
image_train: True
num_gpus: 1
train_small_res: True
loading_imgs: True

# No need to change
hydra:
  run:
    dir: "."
  output_subdir: ~

use_pretrained_classifier: True
pretrained_classifier_path: "/root/.cache/huggingface/hub/models--haiwen--loftup-dinov2s_reg/snapshots/35b4fc9287c0411c1b68abfe47b43d5b36965792/pytorch_modecocostuff_224_classifier.ckpt"
visualize: True